export { default as HomePage } from './Home/Home'
export { default as ProductsPage } from './Products/Products'
export { default as AccessoriesPage } from './Accessories/Accessories'
export { default as CollectionsPage } from './Collections/Collections'
export { default as SalePage } from './Sale/Sale'
export { default as GiftPage } from './Gift/Gift'
export { default as LoginPage } from './Login/Login'
export { default as RegisterPage } from './Register/Register'
